### ISSUE TITLE
Implement responsive design for better mobile and tablet experience

### ISSUE THREAD

**Issue by xaexgit** [xaexgit/hakomsoft_privacypolicy#1]
Currently, the website needs improvements to be fully responsive across all devices. Here are the necessary changes to implement:

### CSS Modifications Needed:

1. **Container Responsiveness**
```css
.container {
    width: 90%;
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}
```

2. **Typography Responsiveness**
```css
/* Mobile-first approach */
h1 { font-size: 24px; }
h2 { font-size: 20px; }
p { font-size: 16px; }

/* Tablet and larger screens */
@media (min-width: 768px) {
    h1 { font-size: 32px; }
    h2 { font-size: 24px; }
    p { font-size: 18px; }
}
```

3. **Policy Sections Responsiveness**
```css
.policy-section {
    padding: 15px;
    margin-bottom: 20px;
}

@media (min-width: 768px) {
    .policy-section {
        padding: 25px;
        margin-bottom: 30px;
    }
}
```

4. **Contact Button Responsiveness**
```css
.contact-btn {
    width: 100%;
    max-width: 300px;
    margin: 0 auto;
    padding: 12px;
    display: block;
}
```

5. **Lists and Content Spacing**
```css
ul {
    padding-left: 20px;
}

li {
    margin-bottom: 10px;
}
```

6. **Flexible Images and Icons**
```css
img, i {
    max-width: 100%;
    height: auto;
}
```

7. **Add Breakpoints for Different Devices**
```css
/* Small devices (phones) */
@media (max-width: 576px) {
    /* Mobile-specific styles */
}

/* Medium devices (tablets) */
@media (min-width: 577px) and (max-width: 992px) {
    /* Tablet-specific styles */
}

/* Large devices (desktops) */
@media (min-width: 993px) {
    /* Desktop-specific styles */
}
```

8. **Floating Particles Responsiveness**
```css
#particles {
    position: fixed;
    width: 100%;
    height: 100%;
    z-index: -1;
}
```

### Testing Required:
- Test on various devices (phones, tablets, desktops)
- Test in different orientations (portrait and landscape)
- Test with different content lengths
- Verify all interactive elements are easily clickable on mobile
- Check text readability across all screen sizes
